#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : compile.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for compiling the simulation design source files
#
# Generated by Vivado on Wed Sep 02 21:47:03 +07 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: compile.sh
#
# ****************************************************************************
set -Eeuo pipefail

xv_cxl_lib_path=""
xv_cpt_lib_path=""
xv_ext_lib_path=""
xv_boost_lib_path="/home/dinhkhanhdang/Applications/xilinx/Vivado/2023.2/tps/boost_1_72_0"

# compile C design sources
echo "xsc -c --gcc_compile_options "-I$xv_boost_lib_path" -work xil_defaultlib -f tb_sha256_top_c.prj"
xsc -c --gcc_compile_options "-I$xv_boost_lib_path" -work xil_defaultlib -f tb_sha256_top_c.prj 2>&1 | tee -a compile.log &
XSC_C_PID=$!

# compile Verilog/System Verilog design sources
echo "xvlog --incr --relax -L uvm -prj tb_sha256_top_vlog.prj"
xvlog --incr --relax -L uvm -prj tb_sha256_top_vlog.prj 2>&1 | tee compile.log

echo "Waiting for jobs to finish..."
wait $XSC_C_PID
echo "No pending jobs, compilation finished."
