#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Sep 02 21:47:07 +07 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
[ -z "$LIBRARY_PATH" ] && export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu || export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH
set -Eeuo pipefail

xv_cxl_lib_path=""
xv_cpt_lib_path=""
xv_ext_lib_path=""
xv_boost_lib_path="/home/dinhkhanhdang/Applications/xilinx/Vivado/2023.2/tps/boost_1_72_0"

# link design libraries
echo "xsc --shared -lib xil_defaultlib -o libdpi.so"
xsc --shared -lib xil_defaultlib -o libdpi.so

# elaborate design
echo "xelab --incr --debug typical --relax --mt 8 --include "$xv_boost_lib_path" -cc_db sha256_coverage -cc_libs -cc_type sbct -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -sv_root "." -sc_lib libdpi.so --snapshot tb_sha256_top_behav xil_defaultlib.tb_sha256_top xil_defaultlib.glbl -log elaborate.log"
xelab --incr --debug typical --relax --mt 8 --include "$xv_boost_lib_path" -cc_db sha256_coverage -cc_libs -cc_type sbct -L xil_defaultlib -L uvm -L unisims_ver -L unimacro_ver -L secureip -sv_root "." -sc_lib libdpi.so --snapshot tb_sha256_top_behav xil_defaultlib.tb_sha256_top xil_defaultlib.glbl -log elaborate.log

