#!/usr/bin/env bash
# ****************************************************************************
# Vivado (TM) v2023.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Sep 03 14:16:43 +07 2026
# SW Build 4029153 on Fri Oct 13 20:13:54 MDT 2023
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
[ -z "$LIBRARY_PATH" ] && export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu || export LIBRARY_PATH=/usr/lib/x86_64-linux-gnu:$LIBRARY_PATH
set -Eeuo pipefail

export xv_cxl_lib_path=""
export xv_cxl_ip_path="$xv_cxl_lib_path/ip"
export xv_cpt_lib_path=""
xv_ext_lib_path=""

xv_ref_path=${VIVADO_LOC:-"/home/dinhkhanhdang/Applications/xilinx/Vivado/2023.2"}
xv_lib_path="$xv_ref_path/lib/lnx64.o/Default:$xv_ref_path/lib/lnx64.o"

export LD_LIBRARY_PATH=$PWD:$xv_lib_path::$LD_LIBRARY_PATH

# simulate design
echo "xsim tb_sha256_top_behav -key {Behavioral:sim_1:Functional:tb_sha256_top} -tclbatch tb_sha256_top.tcl -log simulate.log"
xsim tb_sha256_top_behav -key {Behavioral:sim_1:Functional:tb_sha256_top} -tclbatch tb_sha256_top.tcl -log simulate.log

